services:
  db:
    image: mysql:8.0
    container_name: fabric_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7.2-alpine
    container_name: fabric_redis
    restart: always

  backend:
    image: ${DOCKERHUB_USERNAME}/bingo-backend:latest
    container_name: fabric_backend
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - STORAGE_ENV=prod
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      - db
      - redis

  frontend:
    image: ${DOCKERHUB_USERNAME}/bingo-frontend:latest
    container_name: fabric_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
  backend_uploads:
