"""split quantity to length

Revision ID: 322c43907eab
Revises: e9762f27cd78
Create Date: 2026-06-17 21:50:46.774302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '322c43907eab'
down_revision: Union[str, Sequence[str], None] = 'e9762f27cd78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('length_meters', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('cart_items', sa.Column('units', sa.Integer(), nullable=False))
    op.drop_column('cart_items', 'quantity_meters')
    op.add_column('order_items', sa.Column('length_meters', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('order_items', sa.Column('units', sa.Integer(), nullable=False))
    op.drop_column('order_items', 'quantity_meters')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('quantity_meters', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_column('order_items', 'units')
    op.drop_column('order_items', 'length_meters')
    op.add_column('cart_items', sa.Column('quantity_meters', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_column('cart_items', 'units')
    op.drop_column('cart_items', 'length_meters')
    # ### end Alembic commands ###
