"""add_image_url_and_video_url_to_product_models

Revision ID: 3485608195e5
Revises: ee8b69cacb9c
Create Date: 2026-07-23 21:18:38.610173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3485608195e5'
down_revision: Union[str, Sequence[str], None] = 'ee8b69cacb9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_models', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('product_models', sa.Column('video_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_models', 'video_url')
    op.drop_column('product_models', 'image_url')
    # ### end Alembic commands ###
