"""Add deadline_date to Region

Revision ID: 42da4ba425d5
Revises: 9c40a19a45b4
Create Date: 2026-06-25 11:17:25.478087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42da4ba425d5'
down_revision: Union[str, Sequence[str], None] = '9c40a19a45b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('deadline_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'deadline_date')
    # ### end Alembic commands ###
