"""Add season archives

Revision ID: 4ec3e9d7d92c
Revises: ab55fef9aad8
Create Date: 2026-06-28 20:05:42.331700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec3e9d7d92c'
down_revision: Union[str, Sequence[str], None] = 'ab55fef9aad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season_archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_name', sa.String(length=255), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_archives_id'), 'season_archives', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_season_archives_id'), table_name='season_archives')
    op.drop_table('season_archives')
    # ### end Alembic commands ###
