"""make region_id nullable

Revision ID: 68dab59c5937
Revises: 0c5a552295bc
Create Date: 2026-06-18 13:47:53.997318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '68dab59c5937'
down_revision: Union[str, Sequence[str], None] = '0c5a552295bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'region_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('users_ibfk_1'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'regions', ['region_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_ibfk_1'), 'users', 'regions', ['region_id'], ['id'])
    op.alter_column('users', 'region_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
