"""Add TrafficVisit table

Revision ID: 7002387321be
Revises: 40723a3b9d1d
Create Date: 2026-06-17 14:55:08.845894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7002387321be'
down_revision: Union[str, Sequence[str], None] = '40723a3b9d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_visits_id'), 'traffic_visits', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_visits_source'), 'traffic_visits', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_visits_source'), table_name='traffic_visits')
    op.drop_index(op.f('ix_traffic_visits_id'), table_name='traffic_visits')
    op.drop_table('traffic_visits')
    # ### end Alembic commands ###
