"""cascading_deletes

Revision ID: 90173e81b4ab
Revises: 6d1335d542db
Create Date: 2026-06-17 10:21:28.610703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '90173e81b4ab'
down_revision: Union[str, Sequence[str], None] = '6d1335d542db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_items_ibfk_2'), 'cart_items', type_='foreignkey')
    op.drop_constraint(op.f('cart_items_ibfk_1'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'color_skus', ['color_sku_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cart_items', 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('carts_ibfk_1'), 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('color_skus', 'stock_meters',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('color_skus', 'image_url',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint(op.f('color_skus_ibfk_1'), 'color_skus', type_='foreignkey')
    op.create_foreign_key(None, 'color_skus', 'product_models', ['product_model_id'], ['id'], ondelete='CASCADE')
    op.alter_column('order_items', 'color_sku_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('order_items_ibfk_1'), 'order_items', type_='foreignkey')
    op.drop_constraint(op.f('order_items_ibfk_2'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'color_skus', ['color_sku_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('orders_ibfk_1'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_product_models_name'), 'product_models', ['name'], unique=False)
    op.drop_constraint(op.f('product_models_ibfk_1'), 'product_models', type_='foreignkey')
    op.create_foreign_key(None, 'product_models', 'product_types', ['product_type_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('name'), table_name='product_types')
    op.create_index(op.f('ix_product_types_name'), 'product_types', ['name'], unique=True)
    op.drop_column('product_types', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_types', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_product_types_name'), table_name='product_types')
    op.create_index(op.f('name'), 'product_types', ['name'], unique=True)
    op.drop_constraint(None, 'product_models', type_='foreignkey')
    op.create_foreign_key(op.f('product_models_ibfk_1'), 'product_models', 'product_types', ['product_type_id'], ['id'])
    op.drop_index(op.f('ix_product_models_name'), table_name='product_models')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_ibfk_1'), 'orders', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_ibfk_2'), 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(op.f('order_items_ibfk_1'), 'order_items', 'color_skus', ['color_sku_id'], ['id'])
    op.alter_column('order_items', 'color_sku_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'color_skus', type_='foreignkey')
    op.create_foreign_key(op.f('color_skus_ibfk_1'), 'color_skus', 'product_models', ['product_model_id'], ['id'])
    op.alter_column('color_skus', 'image_url',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('color_skus', 'stock_meters',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key(op.f('carts_ibfk_1'), 'carts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_ibfk_1'), 'cart_items', 'carts', ['cart_id'], ['id'])
    op.create_foreign_key(op.f('cart_items_ibfk_2'), 'cart_items', 'color_skus', ['color_sku_id'], ['id'])
    # ### end Alembic commands ###
