"""expand audit logs

Revision ID: a849267a345f
Revises: da8f3cf7d20e
Create Date: 2026-06-29 09:56:08.166659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a849267a345f'
down_revision: Union[str, Sequence[str], None] = 'da8f3cf7d20e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('entity_type', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('changes', sa.JSON(), nullable=True))
    op.alter_column('audit_logs', 'impersonated_user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('audit_logs', 'endpoint',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'action',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('audit_logs', 'endpoint',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('audit_logs', 'impersonated_user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('audit_logs', 'changes')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity_type')
    # ### end Alembic commands ###
