"""Add display_order to products hierarchy

Revision ID: ba38c08a938d
Revises: f134db5fb4aa
Create Date: 2026-06-29 17:44:30.301942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba38c08a938d'
down_revision: Union[str, Sequence[str], None] = 'f134db5fb4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color_skus', sa.Column('display_order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_color_skus_display_order'), 'color_skus', ['display_order'], unique=False)
    op.add_column('product_models', sa.Column('display_order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_product_models_display_order'), 'product_models', ['display_order'], unique=False)
    op.add_column('product_types', sa.Column('display_order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_product_types_display_order'), 'product_types', ['display_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_types_display_order'), table_name='product_types')
    op.drop_column('product_types', 'display_order')
    op.drop_index(op.f('ix_product_models_display_order'), table_name='product_models')
    op.drop_column('product_models', 'display_order')
    op.drop_index(op.f('ix_color_skus_display_order'), table_name='color_skus')
    op.drop_column('color_skus', 'display_order')
    # ### end Alembic commands ###
