"""add fabric_height

Revision ID: d02a36da736e
Revises: 68dab59c5937
Create Date: 2026-06-19 01:21:54.074553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd02a36da736e'
down_revision: Union[str, Sequence[str], None] = '68dab59c5937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_models', sa.Column('fabric_height', sa.Numeric(precision=10, scale=2), server_default='1.50', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_models', 'fabric_height')
    # ### end Alembic commands ###
