"""rename image_url to image_urls json

Revision ID: d69822cbfb3a
Revises: d02a36da736e
Create Date: 2026-06-19 02:40:32.592274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd69822cbfb3a'
down_revision: Union[str, Sequence[str], None] = 'd02a36da736e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color_skus', sa.Column('image_urls', sa.JSON(), nullable=True))
    
    op.execute("""
        UPDATE color_skus 
        SET image_urls = JSON_ARRAY(image_url)
        WHERE image_url IS NOT NULL AND image_url != ''
    """)
    op.execute("""
        UPDATE color_skus 
        SET image_urls = JSON_ARRAY()
        WHERE image_url IS NULL OR image_url = ''
    """)

    op.drop_column('color_skus', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color_skus', sa.Column('image_url', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('color_skus', 'image_urls')
    # ### end Alembic commands ###
