"""Change SeasonArchive to JSON

Revision ID: da8f3cf7d20e
Revises: 2f97e4e08a23
Create Date: 2026-06-28 20:43:19.123504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'da8f3cf7d20e'
down_revision: Union[str, Sequence[str], None] = '2f97e4e08a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season_archives', sa.Column('archive_data', sa.JSON(), nullable=False))
    op.drop_column('season_archives', 'html_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season_archives', sa.Column('html_content', mysql.TEXT(), nullable=False))
    op.drop_column('season_archives', 'archive_data')
    # ### end Alembic commands ###
