"""remove status from cartitem

Revision ID: ee8b69cacb9c
Revises: ba38c08a938d
Create Date: 2026-07-15 13:24:21.258345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ee8b69cacb9c'
down_revision: Union[str, Sequence[str], None] = 'ba38c08a938d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('status', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
