"""Add historical names to OrderItem

Revision ID: f134db5fb4aa
Revises: a849267a345f
Create Date: 2026-06-29 17:31:05.532237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f134db5fb4aa'
down_revision: Union[str, Sequence[str], None] = 'a849267a345f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('historical_product_name', sa.String(length=255), nullable=True))
    op.add_column('order_items', sa.Column('historical_color_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'historical_color_name')
    op.drop_column('order_items', 'historical_product_name')
    # ### end Alembic commands ###
